config/routes.rb
Rails.application.routes.draw do
  resources :listings do
    match '/scrape', to: 'listings#scrape', via: :post, on: :collection
  end
  root to: 'listings#index'
end

app/models/ListingsSpider.rb
require 'kimurai'

class ListingsSpider < Kimurai::Base
  @name = "ListingsSpider"
  @engine = :mechanize
  @start_urls = []
  @config = {}

  def parse(response, url:, data: {})
  end
end

ListingsSpider.crawl!

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/listings_spider.rb
require 'kimurai'

class ListingsSpider < Kimurai::Base
  @name = 'listings_spider'
  @engine = :selenium_chrome

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//div[@class='listing-card__details']").each do |listing|
      item = {}

      item[:address] = listing.css('h2.listing-card__title')&.text&.squish
      # Once this works, it would be good to refactor the fields in bottom to integers.
      item[:rent] = listing.css('p.listing-card__price')&.text&.squish
      item[:sqft] = listing.css('ul.listing-card__title li')[2]&.text&.squish.gsub('Bed', '')
      item[:bedrooms] = listing.css('ul.listing-card__title li')[0]&.text&.squish.gsub('Bath', '')
      item[:bathrooms] = listing.css('ul.listing-card__title li')[1]&.text&.squish.gsub('FT²', '')

      Listing.where(item).first_or_create
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def scrape
    url = 'https://rentals.ca/montreal'
    response = ListingsSpider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash[:notice] = 'Successfully scraped url'
    else
      flash[:alert] = response[:error]
    end
  rescue StandardError => e
    flash[:alert] = "Error: #{e}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def listing_params
    params.require(:listing).permit(:address, :rent, :sqft, :bedrooms, :bathrooms)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :rent, style: "display: block" %>
    <%= form.text_field :rent %>
  </div>

  <div>
    <%= form.label :sqft, style: "display: block" %>
    <%= form.text_field :sqft %>
  </div>

  <div>
    <%= form.label :bedrooms, style: "display: block" %>
    <%= form.text_field :bedrooms %>
  </div>

  <div>
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.text_field :bathrooms %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Address:</strong>
    <%= listing.address %>
  </p>

  <p>
    <strong>Rent:</strong>
    <%= listing.rent %>
  </p>

  <p>
    <strong>Sqft:</strong>
    <%= listing.sqft %>
  </p>

  <p>
    <strong>Bedrooms:</strong>
    <%= listing.bedrooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= listing.bathrooms %>
  </p>

</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>
<%= button_to 'Scrape', scrape_listings_path %>

<h1>Listings</h1>

<div id="listings">
  <% @listings.each do |listing| %>
    <%= render listing %>
    <p>
      <%= link_to "Show this listing", listing %>
    </p>
  <% end %>
</div>

<%= link_to "New listing", new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/scrape.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= link_to 'Go Back', root_path %>

app/views/listings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @listing %>

<div>
  <%= link_to "Edit this listing", edit_listing_path(@listing) %> |
  <%= link_to "Back to listings", listings_path %>

  <%= button_to "Destroy this listing", @listing, method: :delete %>
</div>